import {
    Check,
    ChevronLeft,
    ChevronRight,
    ChevronDown,
    ChevronUp,
    Command,
    Github,
    ExternalLink,
    Linkedin,
    Laptop,
    Loader2,
    Mail,
    Menu,
    MonitorSmartphone,
    Moon,
    SunMedium,
    Twitter,
    X,
  } from "lucide-react"
    
  export const Icons = {
    logo: Command,
    close: X,
    spinner: Loader2,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronDown: ChevronDown,
    chevronUp: ChevronUp,
    sun: SunMedium,
    moon: Moon,
    laptop: Laptop,
    gitHub: Github,
    twitter: Twitter,
    check: Check,
    menu: Menu,
    monitor: MonitorSmartphone,
    linkedin: Linkedin,
    mail: Mail,
    external: ExternalLink
  }
  