import {
    AlertTriangle,
    ArrowRight,
    Check,
    ChevronLeft,
    ChevronRight,
    ChevronDown,
    Command,
    CreditCard,
    Github,
    File,
    FileText,
    HelpCircle,
    Image,
    Linkedin,
    Laptop,
    Loader2,
    Mail,
    Menu,
    MonitorSmartphone,
    Moon,
    MoonStar,
    MoreVertical,
    Pizza,
    Plus,
    Settings,
    Sun,
    SunMedium,
    Trash,
    Twitter,
    User,
    X,
    type Icon as LucideIcon,
  } from "lucide-react"
  
  export type Icon = LucideIcon
  
  export const Icons = {
    logo: Command,
    close: X,
    spinner: Loader2,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronDown: ChevronDown,
    trash: Trash,
    post: FileText,
    page: File,
    media: Image,
    settings: Settings,
    billing: CreditCard,
    ellipsis: MoreVertical,
    add: Plus,
    warning: AlertTriangle,
    user: User,
    arrowRight: ArrowRight,
    help: HelpCircle,
    pizza: Pizza,
    sun: SunMedium,
    moon: Moon,
    laptop: Laptop,
    gitHub: Github,
    twitter: Twitter,
    check: Check,
    menu: Menu,
    monitor: MonitorSmartphone,
    linkedin: Linkedin,
    mail: Mail,
  }
  